# Generated by Django 5.1.15 on 2026-04-18 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0002_alter_fileupload_file"),
        ("projects", "0034_project_annotator_evaluation_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["project", "fingerprint"], name="data_import_fu_proj_fp_idx"
            ),
        ),
    ]
